###
POST http://localhost:5000/analise
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="example.pdf"
Content-Type: application/pdf

< ./exemplo.pdf
--WebKitFormBoundary--
